import os
from datetime import datetime

from dotenv import load_dotenv
from playwright.async_api import Page

load_dotenv("secrets.env")

FORMATTED_PHONE_NUMBER = os.getenv("FORMATTED_PHONE_NUMBER")


# KIJIJI FUNCTIONS
async def check_logged_in_kijiji(page):
    """
    Check if the user is currently logged in to Kijiji.

    This function looks for a specific element (the 'Ad Details' heading) that is only visible when a user is logged in.

    Args:
        page: The Playwright page object representing the current browser page.

    Returns:
        bool: True if the user is logged in, False otherwise.
    """
    return await page.get_by_role("heading", name="Ad Details").is_visible()


async def format_to_kijiji_date(date):
    central_date = datetime.strptime(date, "%Y-%m-%d")
    return central_date.strftime("%d/%m/%Y")


async def post_on_kijiji(page: Page, relevant_property):
    KIJIJI_DATE = await format_to_kijiji_date(relevant_property["date_available"])

    # property type
    if relevant_property["type"] == "basement":
        await page.get_by_text("Basement").click()
    else:
        await page.get_by_text("House", exact=True).click()

    # number of beds and baths
    await page.locator("#numberbedrooms_s").select_option(
        str(relevant_property["bedrooms"])
    )
    await page.locator("#numberbathrooms_s").select_option(
        f"{relevant_property['bathrooms']}0"
    )

    await page.get_by_text("Year").click()

    # date available
    await page.locator("#dateavailable").click()
    await page.locator("#dateavailable").fill(KIJIJI_DATE)
    await page.locator("#dateavailable").press("Enter")

    # pet-friendly - always no
    await page.get_by_text("No").first.click()

    # size
    await page.locator("#areainfeet_i").click()
    await page.locator("#areainfeet_i").fill(str(relevant_property["sqft"]))

    # funished - always no
    await page.get_by_text("No").nth(1).click()

    # appliances
    await page.get_by_text("Laundry (In Building):").click()
    await page.get_by_text("Fridge / Freezer:").click()

    # air conditioning
    await page.get_by_text("Yes").nth(2).click()

    # personal outdoor space
    await page.get_by_text("Yard:").click()

    if not relevant_property["type"] == "basement":
        await page.get_by_text(
            "Balcony:"
        ).click()  # add logic to only click this if property is main floor

    # smoking - always no
    await page.locator("label").filter(has_text="No").nth(3).click()

    # accessibility - always no
    await page.locator("label").filter(has_text="No").nth(4).click()

    # parking spots
    await page.locator("#numberparkingspots_s").select_option("2")

    # ad title
    await page.get_by_role("textbox", name="Ad title:").click()
    await page.get_by_role("textbox", name="Ad title:").fill(relevant_property["title"])

    # ad description
    await page.get_by_role("textbox", name="Description:").click()
    await page.get_by_role("textbox", name="Description:").fill(
        relevant_property["description"]
    )

    # tags
    # add logic for this to be generated by llm, and formatted to fit json properly
    for tag in relevant_property["tags"]:
        await page.get_by_role("textbox", name="Tags: (optional)").click()
        await page.get_by_role("textbox", name="Tags: (optional)").fill(tag)
        await page.get_by_role("textbox", name="Tags: (optional)").press("Enter")

    # 1. add photos
    property_images = relevant_property["images"]

    # This bypasses the click and the file browser window entirely
    await page.set_input_files(
        "input[type='file']",
        property_images,
    )

    # # WAIT FOR IMAGES TO UPLOAD
    await page.wait_for_timeout(5000)

    # location
    await page.get_by_role("button", name="Change my location").click()
    await page.locator('textarea[name="location"]').fill(
        relevant_property["kijiji_formatted_address"]
    )  # TODO: add kijiji_formatted address field
    await page.get_by_role("option", name="49 Wantanopa Crescent,").click()
    await (
        page.locator(".slider-1136925655").first.click()
    )  # click to show exact property location, useful, so no annoying questions

    # price
    await page.locator("#PriceAmount").click()
    await page.locator("#PriceAmount").fill(str(relevant_property["rent"]))

    # phone number
    await page.get_by_role("textbox", name="e.g. 123 456").click()
    await page.get_by_role("textbox", name="e.g. 123 456").fill(
        FORMATTED_PHONE_NUMBER
    )  # don't hardcode this + expose in program

    # posting
    await page.get_by_test_id("package-0-bottom-select").click()
    await page.get_by_test_id("checkout-post-btn").click()

    # processing time
    await page.wait_for_timeout(10000)
